### ISSUE TITLE
Update on AUR

### ISSUE THREAD

**Issue by jhbruhn** [ros-melodic-arch/ros-melodic-gazebo-dev#6] opened 2020-02-14 13:13 UTC
Hi, I have just updated this package on the AUR and only now found out about these git repos. https://aur.archlinux.org/packages/ros-melodic-gazebo-dev/ Are you going to update the other packages as well? I've commented on the AUR but received no response, so I assume those packages are orphaned?

**Comment by jwhendy** [comment] 2020-02-14 15:20
@bionade24 will know a more official answer. He's the owner of those packages and likely the only person who sees AUR comment notifications. That said, he's commented on a ton of them that issues should be opened in this org vs. comments on AUR. [For example](https://aur.archlinux.org/packages/ros-melodic-catkin/).

There are over 200 pkgs, so I'm guessing he picked bigger/common ones and missed this one.

Open to feedback on this approach. Github is far easier to track with respect to what the issue is about, status, linking upstream (many issues that get brought up are not actually related to arch and require patching/notifying the appropriate ROS upstream pkg).

I think github is a far superior way to deal with updates and issues, at the downside of having users confused vs. how the rest of AUR is handled. Apologies for it seeming like no one listened -- we are reasonably active here and will happily look into your issue.

Would you kindly open a PR for your new PKGBUILD? Another github benefit is I can't see easily what's new from your gist, but a PR will highlight this immediately. Thanks!

**Comment by bionade24** [comment] 2020-02-14 16:41
Hello, sorry for not updating this packages. I think I even once reviwed one of your [PKGBUILDs](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ros-melodic-gazebo-dev), but as they weren't following any formalities we  established I haven't merged them, sadly I forgot about this topic. It would be nice to re-orphan this package, so that I can simply update them with a script. Would be nice to not block our development and please open issues on Github in the future.  Thanks!

**Comment by jhbruhn** [comment] 2020-02-14 16:45
Hey there, no problem, I am not trying to harm your project in any way, but obviously you see the downside of only relying on github issues for that and not reacting to submissions on the AUR. I'll re-orphan the package right away so your script can do it's magic.

BTW: How would I best approach adding new packages? I've added them manually to the AUR by now, but it might make sense to let your script/build server/whatever to handle them properly and update them eventually. All in all I prefer your centralised approach, but a little more transparency would be nice. Are for example the scripts open source?

**Comment by acxz** [comment] 2020-02-14 19:18
As for creating new packages, I first make a package request at https://github.com/ros-melodic-arch/ros-melodic-desktop-full 
Then we will create the appropriate directory here and you can submit PRs to it.

**Comment by acxz** [comment] 2020-02-22 01:39
@jhbruhn if you can add bionade24 as a co-maintainer and orphan the ros-melodic packages you currently maintain that would be the best. It would be much appreciated if you can hand the packages over so we maintain them properly in one location. It also makes it easier for the community to work together instead of splintered like this. I hope you understand.

**Comment by bionade24** [comment] 2020-02-22 10:11
> Hey there, no problem, I am not trying to harm your project in any way, but obviously you see the downside of only relying on github issues for that and not reacting to submissions on the AUR. I'll re-orphan the package right away so your script can do it's magic.
> 
> BTW: How would I best approach adding new packages? I've added them manually to the AUR by now, but it might make sense to let your script/build server/whatever to handle them properly and update them eventually. All in all I prefer your centralised approach, but a little more transparency would be nice. Are for example the scripts open source?

Yes, they are. https://github.com/bionade24/aur-ci

**Comment by bionade24** [comment] 2020-02-22 10:15
Would be nice if you transfer this packages the way @acxz  mentioned, too.

**Comment by jhbruhn** [comment] 2020-02-22 20:54
Alright, I just did that. The packages are the following:

```
ros-melodic-cartographer-rviz
ros-melodic-cartographer-ros
ros-melodic-cartographer 
ros-melodic-cartographer-ros-msgs 
ros-melodic-serial
ros-melodic-teb-local-planner
ros-melodic-libg2o
ros-melodic-mbf-costmap-core
ros-melodic-mbf-abstract-core
ros-melodic-mbf-utility
ros-melodic-mbf-msgs
```
Thanks for your commitment for bringing ROS to Arch Linux!

**Comment by acxz** [comment] 2020-02-22 21:07
hmmm we were requesting that you hand over maintainer status to bionade24. After adding him as a co-maintainer you can orphan the package and the maintainer status will go to bionade24, since you cannot control the release process from this github organization, it is important that you do not have access to pushing the packages to the AUR without a proper sync with this github org. Can you please orphan the packages like we have previously requested?

**Comment by jhbruhn** [comment] 2020-02-22 21:26
Whoops, totally forgot about the orphaning. Done now!

**Comment by acxz** [comment] 2020-02-22 22:49
Thanks so much!

I guess now that you know about this github, next time you have any issues please post them here and we gladly accept PRs!

**Closed as completed by acxz** 2020-02-22 22:49 UTC
